apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/djfoley01/node-chatapp:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/djfoley01/node-chatapp:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: node-chatapp
        chartPath: charts/node-chatapp
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/djfoley01/node-chatapp"
          image.tag: "{{.DIGEST_HEX}}"
